<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="shubham-dhiman" failures="1" tests="2" name="Default test" time="20.25" errors="0" timestamp="2024-10-22T16:18:51 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.935"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.589">
    <failure type="java.lang.AssertionError" message="Forcefully failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Forcefully failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at pageObjects.LoginPage.failedscenrios(LoginPage.java:74)
at stepDefinations.LoginPageStepDef.verify_failure(LoginPageStepDef.java:35)
at âœ½.verify failure(file:///C:/Users/shubham.dhiman/Desktop/Temp/JenkinsGithubDemo/src/test/java/Features/1.Login.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
